renamed files and folders to fit new repo name
AtMoDat/atmodat_data_checker pull request #24
Opened 2021-02-02 13:55 UTC by am-kaiser

Changed names of files and folder to fit the new name of this repository.

2021-02-08 09:17 UTC, jkretz requested changes
LGTM 
Just a comma is missing

2021-02-08 09:17 UTC, jkretz commented on README.md
> +Its core functionality is based on the [IOOS compliance checker](https://github.com/ioos/compliance-checker). The AtMoDat Standard Compliance Checks library makes use of [cc-yaml](https://github.com/
```suggestion
Its core functionality is based on the [IOOS compliance checker](https://github.com/ioos/compliance-checker). The AtMoDat Standard Compliance Checks library makes use of [cc-yaml](https://github.com/cedadev/cc-yaml), which provides a plugin for the [IOOS compliance checker](https://github.com/ioos/compliance-checker) that generates check suites from YAML descriptions. Furthermore, the [Compliance Check Library](https://github.com/cedadev/compliance-check-lib) is used as the basis to define generic, reusable compliance checks. This repository is an extension of this library as it holds specific checks to ensure compliance with the AtMoDat Standard. Moreover, it contains checks to verify the compliance to the [AtMoDat CVs](https://github.com/AtMoDat/AtMoDat_CVs).
```

2021-02-09 13:05 UTC, jkretz approved these changes

2021-02-10 13:02 UTC, jkretz commented
I am about to merge this branch into the master. Before doing so, I want to unify the run_checks.bash and run_checks_folder.bash

2021-02-10 13:05 UTC, am-kaiser commented
> 
> 
> I am about to merge this branch into the master. Before doing so, I want to unify the run_checks.bash and run_checks_folder.bash

Thanks!

2021-02-11 13:58 UTC, jkretz commented
I replaced `run_checks.bash` and `run_checks_folder.bash` with `run_checks.py`. This python scirpt can also be used to quickly summarize the results of the respective checker in the future. Furthermore, this script can also be used to convert the `*.txt` from the cfchecker into a `*.json` in the future as well.

2021-02-12 14:25 UTC, merged