added summary of output
AtMoDat/atmodat_data_checker pull request #28
Opened 2021-03-10 12:23 UTC by am-kaiser

branch includes scripts to create a short and detailed summary of the checker output

2021-03-24 17:37 UTC, atmodatcode approved these changes

2021-03-29 09:45 UTC, jkretz requested changes
Everything looks okay to me in principle. I attached some parts that should be revised.
Furthermore, I have a hard time to interpret the output of the `detailed_summary.csv` as there is quite a lot information, especially in the `msgs` column, which is not that nicely formatted (at least when openiing it with Libre Office).
Before merging, I would recommend to squash all commits into one.

2021-03-29 09:45 UTC, jkretz commented on atmodat_data_checker/result_output/output_directory.py
> +now_formatted = now.strftime("%Y%m%d_%H%M") + '/'
I don't like the output of the checkers to be placed in a directory labeled with the date. It might be a little hard to follow what results are in which directory if you do checks on multiple files and directories. So why not label it after the name of the file or the directory the files to be checked are in?

2021-03-29 09:45 UTC, jkretz commented on atmodat_data_checker/result_output/output_directory.py
> +        os.system('mkdir -p ' + opath)
This won't work on Windows machines. To be platform-independent use `os.mkdir(opath)`

2021-03-29 09:45 UTC, jkretz commented on atmodat_data_checker/result_output/output_directory.py
> +            os.system('mkdir -p ' + opath + '/' + check)
Same here

2021-03-29 09:45 UTC, jkretz commented on atmodat_data_checker/result_output/summary_creation.py
> +import pandas as pd
Pandas is not part of the modules that are installed in the processes of setting up the Atmodat checkers. This should therefore mentioned in the requirements

2021-03-31 16:15 UTC, atmodatcode commented on atmodat_data_checker/result_output/output_directory.py
> +now_formatted = now.strftime("%Y%m%d_%H%M") + '/'
I will think about this and revise it, but for now, I will keep it for testing the new summary module.

2021-03-31 16:20 UTC, merged